# Generated by Django 4.1.4 on 2023-05-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Names',
        ),
    ]
